project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  pdf: default
  html:
    comments:
      hypothesis: true
    header-includes:
      - |
        <style>
          body {
            text-align: justify;
          }
        </style>

execute:
  freeze: auto