---
title: Analyzing Satellite Scaling Bias Using Drone Data, Application to Microphytobenthos Studies
authors:
  - name: Augustin Debly
    affiliation: Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
    orcid: "0009-0000-7194-7099"
    roles: writing
    corresponding: true
bibliography: references.bib
---

# Introduction
The present study focuses on microphytobenthos (MPB) colonizing estuarine intertidal zones. MPB refers to photosynthetic unicellular microalgae forming biofilms at the sediment surface during low tides. This group includes diatoms, euglenids, cyanobacteria, and chlorophyta [@underwood_microphytobenthos_2001]. They can be associated to mud and sand, i.e. inorganic particles with size between 4 and 63µm, and 63 and 2000µm, respectively [@wentworth_scale_1922]. In these soft-bottom sediments, MPB can be the main primary producer, notably in turbid estuaries.

MPB provides several ecosystem services [@hope_role_2020]. In addition to its contribution to carbon fluxes, estimated between 30 and 230 g C/m²/year [@heip_production_1995 ;@park_harnessing_2024], it stabilizes the sediment through the secretion of extracellular polymeric substances (EPS) [@gibbs_effect_1983 ; @riethmuller_chlorophyll_2000 ; @stal_microphytobenthos_2010 ; @huiming_floc_2011 ; @fang_effect_2012 ; @gerbersdorf_exploring_2020], and therefore reduces coastal erosion [@hope_role_2020]. It is a key element of food webs (Deppe, 1999; Aberle-Malzahn, 2004; Dauvin and Desroy, 2005), and it plays an important role in nutrient cycling, increasing water quality. It can also be used as a bioindicator of water quality [@oiry_using_2021].

# Material and methods

# Results

# Discussion

# References
