---
title: Analyzing Satellite Scaling Bias Using Drone Data, Application to Microphytobenthos Studies
authors:
  - name: Augustin Debly
    affiliation: Institut des Substances et Organismes de la Mer, ISOMer, Nantes Université, UR 2160, F-44000 Nantes, France
    orcid: "0009-0000-7194-7099"
    roles: writing
    corresponding: true
bibliography: references.bib
---

# Introduction

## MPB

The present study focuses on microphytobenthos (MPB) colonizing estuarine intertidal zones. MPB refers to photosynthetic unicellular microalgae forming biofilms at the sediment surface during low tides. This group includes diatoms, euglenids, cyanobacteria, and chlorophyta [@underwood_microphytobenthos_2001]. They can be associated to mud and sand, i.e. inorganic particles with size between 4 and 63µm, and 63 and 2000µm, respectively [@wentworth_scale_1922]. In these soft-bottom sediments, MPB can be the main primary producer, notably in turbid estuaries.

## Ecological services

MPB provides several ecosystem services [@hope_role_2020]. In addition to its contribution to carbon fluxes, estimated between 30 and 230 g C/m²/year [@heip_production_1995; @park_harnessing_2024], it stabilizes the sediment through the secretion of extracellular polymeric substances (EPS) [@gibbs_effect_1983; @riethmuller_chlorophyll_2000; @stal_microphytobenthos_2010; @huiming_floc_2011; @fang_effect_2012; @gerbersdorf_exploring_2020], and therefore reduces coastal erosion [@hope_role_2020]. It is a key element of food webs [@deppe_intertidal_1999; @aberle-malzahn_microphytobenthos_2004; @dauvin_food_2005], and it plays an important role in nutrient cycling, increasing water quality. It can also be used as a bioindicator of water quality [@oiry_using_2021].

## Spatial structure

The MPB exhibits spatial variability at different scales

```{r}
#| label: fig-resolutions
#| fig-cap: "Resolutions of x different sensors cross represented with the different spatial scales of MPB"
#| fig-width: 10
#| fig-height: 10
#| cache: true
#| echo: false
#| eval: true
#| warning: true

library(viridis)

xmin = -7
xmax = 6

ymin = -7
ymax = 6

npixmax = 1e4

par(mar = c(5,5,2,2))

plot(c(),c(),xlab = "Resolution",ylab = "Swath",xaxt="n",yaxt="n",xlim=c(xmin,xmax),ylim = c(ymin,ymax),xaxs="i",yaxs="i",asp= 1)

x_fond <- seq(xmin, xmax, length.out = 300)
y_fond <- seq(ymin, ymax, length.out = 300)
z_fond <- outer(x_fond, y_fond, FUN = function(x, y) (10^y)/(10^x))

cols <- magma(n = 1000,alpha = 0.2)

image(x_fond, y_fond, log10(z_fond), col = cols, zlim = log10(c(1, npixmax)),add=T)

X    = 10^(seq(xmin,xmax))
Y    = 10^(seq(ymin,ymax))

for(x in X){
  lines(log10(c(x,x)),c(ymin,ymax),lty=1,col=rgb(0,0,0,0.2))
}

for(x in c(2*X[-length(X)],3*X[-length(X)],4*X[-length(X)],5*X[-length(X)],6*X[-length(X)],7*X[-length(X)],8*X[-length(X)],9*X[-length(X)])){
  lines(log10(c(x,x)),c(ymin,ymax),lty=2,col=rgb(0,0,0,0.1))
}

for(y in Y){
  lines(c(xmin,xmax),log10(c(y,y)),lty=1,col=rgb(0,0,0,0.2))
}

for(y in c(2*Y[-length(Y)],3*Y[-length(Y)],4*Y[-length(Y)],5*Y[-length(Y)],6*Y[-length(Y)],7*Y[-length(Y)],8*Y[-length(Y)],9*Y[-length(Y)])){
  lines(c(xmin,xmax),log10(c(y,y)),lty=2,col=rgb(0,0,0,0.1))
}

axis(1,at=log10(X),labels = c("100 nm","1 µm","10 µm","100 µm","1 mm","1 cm","1 dm","1 m","10 m","100 m","1 km","10 km","100 km","1000 km"),cex.axis=0.8)
axis(2,at=log10(Y),labels = c("100 nm","1 µm","10 µm","100 µm","1 mm","1 cm","1 dm","1 m","10 m","100 m","1 km","10 km","100 km","1000 km"),cex.axis=0.8)

polygon(c(xmin,xmax,xmax,xmin), c(xmin,xmin,xmax,xmin), col = "white", border = "black")
polygon(c(xmin,log10((10^ymax)/npixmax),xmin,xmin), c(log10(npixmax*10^xmin),ymax,ymax,log10(npixmax*10^xmin)), col = "white", border = "black")

H  = seq(12,120,0.1)
N  = 1088
SW = N*0.00345/1000
FR = 5.5/1000
DW = H*SW/FR
SR = DW/N

lines(log10(SR),log10(DW))
points(c(min(log10(SR)),max(log10(SR))),c(min(log10(DW)),max(log10(DW))))

liste_res_sat = c(10)
liste_cov_sat = c()

```

## MPB & RS

## The use of a proxy

NDVI can be transformed into biomass following [@eq-NDVIB]

$$
B_{a,b,c}(NDVI) = \frac{1}{c}ln\left(\frac{b}{a+b-NDVI}\right)
$$ {#eq-NDVIB}

## Bias

## Present study

# Material and methods

## Simulating a satellite dataset from a drone dataset

The choice has been made to simulate coarser dataset from drone fine-scale

## 

# Results

# Discussion

# References
